### ISSUE TITLE
registration paymentManager instruments .set 'instrument-key' handler payment

### ISSUE THREAD

**Issue by MimiaBena** [w3c/webpayments-payment-apps-api#410] opened 2023-02-15 10:19 UTC
Hello,

I create a service worker and a payment manager they are well registered on my browser. I made an instrument set but I can't find the instrument to register with the payment methods and when I look at the payment process, the instrument key is empty.

`  console.log(navigator.serviceWorker.ready)
    return navigator.serviceWorker.ready;
}).then((registration) => {
    console.log(registration)
    
    if (!registration.paymentManager) {
        console.log('No payment handler capability in this browser. Is chrome://flags/#service-worker-payment-apps enabled?');
        return;
    }
    if (!registration.paymentManager.instruments) {
        console.log('Payment handler is not fully implemented. Cannot set the instruments.');
        return; 
    }
    registration.paymentManager.instruments
        .set('instrument-key', {
            name: 'Chrome uses name and icon from the web app manifest',
            enabledMethods: ['https://paymentTrequest.fr'],
            method: 'https://paymentTrequest.fr',
            capabilities: {supportedNetworks: ['yo', 'rt'],
            supportedTypes: ['debit', 'credit']}
        
        })`
Any help please

**Comment by ianbjacobs** [comment] 2023-02-16 16:12
cc @rsolomakhin

**Comment by stephenmcgruer** [comment] 2023-02-17 20:10
Hi there; thanks for filing the issue. Unfortunately `PaymentManager.Instruments` has been removed from the Payment Handler specification (https://github.com/w3c/payment-handler/pull/409) and from Chromium as of M111 (currently in Beta, to be released to Stable in early March).

The concept of a browser-managed instruments never fully matured in the ecosystem, and instead things moved in the direction of just having a payment app which is responsible for handling whatever payment methods it wants to internally to its own logic (server and client).

The still-supported way to install such a payment app is via the JIT path that is mentioned in the spec [here](https://w3c.github.io/payment-handler/#just-in-time-registration), but which there is also a web.dev article on that may be useful - https://web.dev/setting-up-a-payment-method/

I hope that this helps!

**Comment by MimiaBena** [comment] 2023-02-23 08:26
Thank you for your response!


I wanted to put in place with the payment request traditionnel  the SPC ( secure payment request)
do I have to put the 2 or it is not feasible and how to integrate the secure payment request into the traditional payment request

Thanks for your help

**Comment by stephenmcgruer** [comment] 2023-02-24 15:46
I'm not quite sure I am interpreting you correctly, but to go through a few scenarios:

1. If you want to trigger SPC in general, you can create a PaymentRequest object with a `supportedMethods` of 'secure-payment-confirmation'. See https://developer.chrome.com/articles/secure-payment-confirmation/ for more

2. If you want to trigger SPC from a web-based Payment Handler, that is unfortunately not currently possible in Chrome :(. If you have a use-case for doing so, please file an issue [here](https://github.com/w3c/secure-payment-confirmation/issues) on the SPC repo. So far we have not heard from anyone who is using both Payment Handler **and** SPC for the same product, but we'd love to discover new use-cases! :)

Hopefully one of these above answers your question.

**Comment by MimiaBena** [comment] 2023-02-24 16:00
thank you for your response.

another question on the payment request I didn't want to display the delivery address but I can't get it, what do I have to do to remove it. il want just the detail order and metode payment 

`
       const supportedInstruments = [{
           supportedMethods: 'https://ipayreq...',
       
          }];
          
          const details = {
           id: 'order-123',
           displayItems: [
             {
               label: "Sub-total",
               amount: { currency: "EUR", value: "55.00" },
             },
             {
               label: "T",
               amount: { currency: "EUR", value: "115.00" },
             },
             {
               label: "Art",
               amount: { currency: "EUR", value: "5.00" },
             },
           ],
           total: {
             label: "Total",
           
             amount: { currency: "EUR", value: "65.00" },
           },
          };
          
          const options = {requestShipping: true};
          const request =new PaymentRequest(supportedInstruments, details, options);   `


Thank you thank you

**Comment by stephenmcgruer** [comment] 2023-02-27 15:34
You are passing `options = {requestShipping: true}`, which will trigger address collection. If you remove that option, Chrome will not prompt the user to provide a shipping address.

Note however that if you don't request shipping in the example you give above, I think you might trigger the [skip the sheet](https://web.dev/setting-up-a-payment-method/#how-browsers-can-skip-the-payment-request-ui-and-launch-a-payment-app-directly) behavior and end up directly at whatever payment app you are specifying in `supportedInstruments` (if you are only specifying one). It is a fair point that I'm not sure if it's possible in Chrome to get a browser sheet UI that shows only the order details and nothing else - we assume that the payment app will also show the order details in that case.

**Comment by MimiaBena** [comment] 2023-03-19 19:30
Hello,

I followed the tutorial to create a payment method with the manifest and a service worker it works fine
I added my method with "navigator.paymentMananager.instruments.set" but this part is removed. I haven't found an alternative to this.

  now i have an error that my method is not supported are there any updates on payment method integration


Thanks for helps

**Comment by stephenmcgruer** [comment] 2023-03-20 14:33
@MimiaBena - without sample code or (preferably) a publicly visible reproduction webpage, I'm afraid I doubt we will be able to help you. Payment Handler should work for manifest+service-worker payment methods, and I cannot tell from your post why you would see method not supported.

> I added my method with "navigator.paymentMananager.instruments.set" but this part is removed. I haven't found an alternative to this.

There is no alternative; the concept of specific instruments has been removed from Payment Handler and the handling of payment instruments is now an internal detail of the payment app declared in the manifest (e.g., entirely up to whatever the service worker code does.)

**Comment by MimiaBena** [comment] 2023-03-20 14:54
my manifest is:
```
{
  "default_applications": ["https://testpr.fr/manifest.json"],
  "supported_origins": ["https://testpr.fr"]
}
```

My installer:

`function install(){
	hideElements();
if ('serviceWorker' in navigator) {
navigator.serviceWorker.register('sw.js').then((reg) => {
	return navigator.serviceWorker.ready;
})
})
.catch((error) => {
	console.log('error is' + error);
});
}
else {
    alert('service worker not available on this browser');
  }
}
`


My server Worker:

````
self.addEventListener('canmakepayment', e => {
	console.log('canmakepayment', e);
  e.respondWith(new Promise(function(resolve, reject) {
    resolve(true);
  }));
});
async function waitForMessage() {
	return new Promise((resolve, reject) => {
	  self.addEventListener('message', listener = e => {
		self.removeEventListener('message', listener);
		if (!e.data || !e.data.methodName ) {
			reject();
			return;
		}
    try {
      switch (e.data.type) {
        case 'WINDOW_IS_READY':
          resolve(e.data);
          break;
      }
    }catch (error) {
      resolver.reject();
      payment_request_event = null;
    }
		
	});
});
}
self.addEventListener('paymentrequest', evt => {
evt.respondWith((async() => {
	const windowClient = await evt.openWindow('check.html');
	  windowClient.postMessage( {
......
    });
	  const result = await waitForMessage();
	  return result;
	})());
	
  });
// Define a convenient `postMessage()` method
const postMessage = (type, contents = {}) => {
  if (client) client.postMessage({ type, ...contents });
}


```

My show function:

```
  if(window.PaymentRequest) {
 
      const supportedInstruments = [{
       
         supportedMethods: "https://testpr.fr",
          data: {
           ...
          }
         }];
         
         const details = {
        ....
          ],
          total: {
           ...
          }
         };  
         const options = {requestPayerName: true, requestShipping: false};
         const request =new PaymentRequest(supportedInstruments, details, options);   
       
         try {
          const response = await request.show();
          console.log(response);  
          window.setTimeout(function() {
            response.complete('success')
            .then(function() {

             alert('payment accepted')
             console.log('succes')
            })
            .catch(function(err) {
              ChromeSamples.setStatus(err);
            });

        }, 2000);
        } catch (err) {
         
          console.error("Uh oh, something bad happened", err.message);
        }
     
} else {
// Fallback to traditional checkout
alert('PaymentRequest not supported');
}
```


I have error : https://testpr.fr is not supported


Thank you

**Comment by stephenmcgruer** [comment] 2023-03-20 15:20
I'm assuming here that `https://testpr.fr/manifest.json` is an example URL, since that 404s in my browser. Not having a real reproduction website makes this a little harder to understand.

Anyway, some high level notes:

1. The installer is no longer necessary (though I think it technically should work) - the PaymentRequest.show() call will do the install for you when it encounters the payment method manifest.
2. You don't actually show the contents of the web app manifest (https://testpr.fr/manifest.json) in your comment above, knowing that would be helpful.
3. Your Payment Request code looks roughly correct, **assuming** that at https://testpr.fr one can find either the payment method manifest you include above, or that it responds with a Link header pointing to the manifest (as [described here](https://web.dev/setting-up-a-payment-method/#optionally-route-the-browser-to-find-the-payment-method-manifest-in-another-location)).

As a suggestion, https://rsolomakhin.github.io/pr/ph-icon-size/ is a demo that trigger a number of different payment handlers (depending on what button is clicked). The individual payment handler's code can be found at e.g. https://rsolomakhin.github.io/pr/apps/icon-sizes/icon-24-test/payment_method_manifest.json . Possibly looking at both the triggering code and the web app manifest+code may help.

**Comment by MimiaBena** [comment] 2023-03-21 07:37
Thank you! 

I put the json url in supported method. I missed that for it to work

   const supportedInstruments = [{
       
         supportedMethods: "https://testpr.fr/manifest-payment.json",
          data: {}
}]


Thank a lot

**Comment by stephenmcgruer** [comment] 2023-03-27 19:57
Closing as the issue appears to be resolved.

**Closed as completed by stephenmcgruer** 2023-03-27 19:57 UTC

**Comment by MimiaBena** [comment] 2023-05-03 14:51
Hello,
I'm using the payment request api so it works well on chrome but when I wanted to test it on opera android I have a problem with the method not supported so I installed a web server but I wanted to do a set of insrumrnt (because it's supported on opera android)

 I have an error 

error isNotAllowedError: Not allowed to install this payment handler
I don't really understand what the error is about.


Thank you
