### ISSUE TITLE
Need to reuse web app manifest ImageResource better.

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#287] opened 2018-04-12 14:54 UTC
[Feedback on Payment Handler TAG review](https://github.com/w3ctag/design-reviews/issues/231#issuecomment-379432134) by @dbaron:

> ImageObject is similar to web app manifest's ImageResource, but it: (1) doesn't have the two last properties, (2) has a differing type for type (DOMString vs. USVString).

IMHO, we should reuse web app manifest's ImageResource verbatim to ease both spec authoring and implementation.

**Comment by domenic** [comment] 2018-04-12 18:07
This is a dupe of https://github.com/w3c/payment-handler/issues/238, where I noted that I think it's actually not a good idea.

**Comment by rsolomakhin** [comment] 2018-04-12 18:11
@dbaron: Would you agree with @domenic's logic in #238?

**Comment by kenchris** [comment] 2018-04-12 21:53
I wouldn't. Platform and purpose are hints, so I don't see why they don't apply, for the same reason they exist in the web app manifest

**Comment by ianbjacobs** [comment] 2018-04-26 20:37
SInce this is a dupe of #238 I am going to close this issue and ping David Baron on that thread.

**Closed as completed by ianbjacobs** 2018-04-26 20:37 UTC
