### ISSUE TITLE
Payment manifest supporting multiple payments apps from different providers?

### ISSUE THREAD

**Issue by arisc097** [w3c/webpayments-payment-apps-api#270] opened 2018-03-23 18:13 UTC
Can you point us to concrete example - as we see this is not working on our side. Happy to share our code example with screenshots.

**Comment by ianbjacobs** [comment] 2018-03-23 18:16
@rsolomakhin, can you lend a hand? Thanks!
Ian

**Comment by rsolomakhin** [comment] 2018-03-23 18:22
[Payment method manifest](https://rsolomakhin.github.io/bobpay/payment-manifest.json)
[Payment app 1](https://rsolomakhin.github.io/pr/apps/bobpay/)
[Payment app 2](https://bobpay.xyz/)

If this does not help, please share your code example. Good luck!

**Comment by majaybabupayment** [comment] 2018-03-23 18:24
I am going to bit expand on the issue @arisc097 is pointing towards -

We have 2 payment origins - xyz.com, abc.com  who have registered the same payment method  alicepay.com.  On the payment manifest if I have just  xyz.com as the supported_origins I still see both abc.com and xyz.com on the payment window when a Payment request is made. Not sure what we are missing here.

Payment manifest is -

{
    "supported_origins": ["https://xyz.com"]
}

Chrome - Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by rsolomakhin** [comment] 2018-03-23 18:26
Not sure what could be the cause of this. Do you also have `"basic-card"` payment method in there perhaps? If you could create a demo that you can share (confidentially is also OK), then I can look into this deeper.

**Comment by rsolomakhin** [comment] 2018-03-23 18:28
Here's a sample where an app cannot be installed because it's not in the `"supported_origins"` list: [Link](https://rsolomakhin.github.io/pr/apps/alice/).

**Comment by rsolomakhin** [comment] 2018-03-23 18:30
It's quite possible, by the way, that Chrome 65 did not have the code to handle the `"supported_origins"` yet. Please use Chrome [Canary](https://www.google.com/chrome/browser/canary.html) or [Dev](https://www.google.com/chrome/browser/index.html?extra=devchannel), which are at version 67.

**Comment by adrianhopebailie** [comment] 2018-03-23 23:00
Also, be sure that the browser is actually finding the manifest (i.e. you are serving the correct headers at alicepay.com that point to your manifest.

**Comment by majaybabu** [comment] 2018-03-24 00:45
Is the payment-manifest.json cached or every time a show() happens on Payment Request it is fetched ?  It worked for us after we updated to Chrome version 67 and reloaded the payments apps.

**Comment by majaybabu** [comment] 2018-03-24 01:49
Is there a way to control the payment app displayed on the first page. In our example payments apps - xyz.com and  abc.com have registered the same payment method alicepay.com. When a Payment request is made on alicepay.com both payment apps are available for selection but how do I control xyz.com to be displayed instead of abc.com on the first page -  Can payment-manifest control this ?

**Comment by rsolomakhin** [comment] 2018-03-24 18:19
The payment manifest is cached after every retrieval and kept for a number of days to help with intermittent connectivity and payment sheet startup time.

The apps are sorted by [frecency](https://en.wikipedia.org/wiki/Frecency) (right, @gogerald?). The app on top will be the app that was used most frequently and recently.

**Comment by adrianhopebailie** [comment] 2018-03-26 14:23
@rsolomakhin does the browser honor cache-control headers?

**Comment by rsolomakhin** [comment] 2018-03-26 14:28
@adrianhopebailie: That's the plan, but not implemented yet. Currently we cache manifests for 90 days. Every `new PaymentRequest(https://foo.com)` will refresh the payment method cache for `https://foo.com`.

**Comment by gogerald** [comment] 2018-03-26 15:43
Yes, the apps are sorted by frecency, and the order between apps haven't been used are 'random' - depends on which one is detected first.

**Comment by ianbjacobs** [comment] 2018-03-29 21:25
@rsolomakhin, @marcoscaceres, do you think we need to say anything about caching of payment method manifests in that specification?

**Comment by ianbjacobs** [comment] 2018-04-02 12:21
The question about app order is covered in our FAQ:
 https://github.com/w3c/payment-request-info/wiki/FAQ#can-merchants-affect-the-order-of-matching-payment-apps-displayed-to-the-user

The question about payment method manifest caching is covered in our payment method good practice document:
 https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice#payment-method-manifest-files

I'm going to close this issue. If there are other topics, let's open a new issue.

Ian

**Closed as completed by ianbjacobs** 2018-04-02 12:21 UTC
