### ISSUE TITLE
normative "A single payment handler should not be allowed to open more than one client window using this method."

### ISSUE THREAD

**Issue by gogerald** [w3c/webpayments-payment-apps-api#169] opened 2017-06-05 13:30 UTC
There is a non-normative note that "A single payment handler should not be allowed to open more than one client window using this method."

Should we normalize it?

**Comment by ianbjacobs** [comment] 2017-06-06 14:26
@romandev, this seems related to #163. It makes sense to move the constraint to the open window algorithm (and out of the Note). Thank you!

Ian

**Comment by romandev** [comment] 2017-06-06 17:29
> @romandev, this seems related to #163. It makes sense to move the constraint to the open window algorithm (and out of the Note). Thank you!

IMHO, the spec algorithm is already explaining the problem.

> If event.[[windowClient]] is not null, then:
> > If event.[[windowClient]].visibilityState is not "unloaded", reject promise with a DOMException whose name is "InvalidStateError" and abort these steps.

When openWindow is called at first time, the [[windowClient]] will be null. But when it is called at the next time, it will not be null and then if the windowClient is *not* unloaded, then, reject InvalidStateError.
In other words, if window is open, then reject promise with InvalidStateError.

But I think it's better to check it before navigation happens.

**Comment by rsolomakhin** [comment] 2017-06-20 14:08
Can we close as "working as intended"? @romandev

**Comment by romandev** [comment] 2017-06-21 12:52
@rsolomakhin I think we can close this issue :-)

**Closed as completed** 2017-06-21 13:36 UTC
